version: 1.0
description: >
  This schema represents the output of an SQL query that analyzes the mental health indicators of international students based on their length of stay. The table provides the number of students, average depression score, average social connectedness score, and average acculturative stress score, grouped by years of stay.

fields:
  - name: stay
    type: integer
    description: "The length of stay of the students in years."

  - name: count_int
    type: integer
    description: "The number of international students for each length of stay."

  - name: average_phq
    type: float
    description: "The average score of the Patient Health Questionnaire (PHQ), measuring the severity of depression."

  - name: average_scs
    type: float
    description: "The average score of the Social Connectedness Scale (SCS), assessing the degree of social connectedness."

  - name: average_as
    type: float
    description: "The average score of the Acculturative Stress Scale (AS), which evaluates the stress levels associated with acculturation."

sorting:
  - column: stay
    direction: desc
    description: "The results are sorted by the length of stay in descending order."

output_format: csv
output_name: result.csv
description: "The output CSV file contains detailed statistics on mental health indicators for international students by length of stay."
